#!/usr/bin/env python3
"""Generates the HVIF vector icon and writes resources/PrinceOfPersia.rdef.

Same isometric slab as the other apps in this collection (R Memo, R Markdown,
R QR Reader...): top face N(32,3) E(62,21) S(32,39) W(2,21), side faces 14
units deep, flat colours with the left face at about 70% and the right face at
about 48% of the top colour.

The slab is a lapis-blue Persian tile. Its top face carries a khatam, the
eight-pointed girih star of Persian tilework, drawn in the same isometric
projection: a gold star, a turquoise star inside it, a cream inner star turned
by 22.5 degrees, and a red centre, with gold diamonds in the corners.

Also writes build/icon.hvif (raw icon data) so the result can be rendered and
checked with tools/rendericon.cpp on Haiku."""
import math
import os

# ---- HVIF encoding ------------------------------------------------------------

def coord(v):
    v = float(v)
    if -32 <= v <= 95 and v == int(v):
        return bytes([int(v) + 32])
    n = int(round((v + 128) * 102))
    return bytes([0x80 | (n >> 8), n & 0xff])

styles, paths, shapes = [], [], []

def style(rgb):
    styles.append(bytes([1]) + bytes(rgb) + bytes([255]))   # STYLE_TYPE_SOLID_COLOR
    return len(styles) - 1

def fill(st, pts):
    paths.append(pts)
    shapes.append((st, len(paths) - 1))

def encode():
    out = bytearray(b'ncif')
    out.append(len(styles))
    for s in styles:
        out += s
    out.append(len(paths))
    for pts in paths:
        out += bytes([(1 << 1) | (1 << 3), len(pts)])        # closed, no curves
        for x, y in pts:
            out += coord(round(x, 2)) + coord(round(y, 2))
    out.append(len(shapes))
    for st, p in shapes:
        out += bytes([10, st, 1, p, 0])                       # path source shape, no flags
    return bytes(out)

# ---- geometry -----------------------------------------------------------------

# Tile space (u, v) in [-1, 1]^2 onto the top face: (-1,-1) is the north corner,
# (1,-1) east, (1,1) south, (-1,1) west.
C = (32.0, 21.0)
A = (15.0, 9.0)
B = (-15.0, 9.0)
DEPTH = 14.0

def P(u, v):
    return (C[0] + u * A[0] + v * B[0], C[1] + u * A[1] + v * B[1])

def star(outer, rotation=0.0):
    """Eight-pointed star (two overlapping squares) centred on the tile."""
    inner = outer * 0.7654
    return [P((outer if k % 2 == 0 else inner) * math.cos(math.radians(rotation + k * 22.5)),
              (outer if k % 2 == 0 else inner) * math.sin(math.radians(rotation + k * 22.5)))
            for k in range(16)]

def octagon(r):
    return [P(r * math.cos(math.radians(22.5 + 45 * k)), r * math.sin(math.radians(22.5 + 45 * k))) for k in range(8)]

def diamond(cu, cv, r):
    return [P(cu + r, cv), P(cu, cv + r), P(cu - r, cv), P(cu, cv - r)]

def shade(rgb, f):
    return tuple(int(round(c * f)) for c in rgb)

# ---- drawing ------------------------------------------------------------------

LAPIS = (0x2f, 0x5f, 0xb8)
top = style(LAPIS)
left = style(shade(LAPIS, 0.69))
right = style(shade(LAPIS, 0.48))
gold_dark = style((0x8c, 0x5e, 0x16))
gold = style((0xe6, 0xb4, 0x4c))
turquoise = style((0x2e, 0xb8, 0xba))
cream = style((0xf8, 0xee, 0xd2))
red = style((0xc4, 0x36, 0x28))

N, E, S, W = P(-1, -1), P(1, -1), P(1, 1), P(-1, 1)
fill(left, [W, S, (S[0], S[1] + DEPTH), (W[0], W[1] + DEPTH)])
fill(right, [E, (E[0], E[1] + DEPTH), (S[0], S[1] + DEPTH), S])
fill(top, [N, E, S, W])

for cu, cv in ((-1, -1), (1, -1), (1, 1), (-1, 1)):
    fill(gold_dark, diamond(cu * 0.80, cv * 0.80, 0.19))
    fill(gold, diamond(cu * 0.80, cv * 0.80, 0.13))

fill(gold_dark, star(0.82))
fill(gold, star(0.75))
fill(turquoise, star(0.62))
fill(gold_dark, star(0.42, 22.5))
fill(cream, star(0.36, 22.5))
fill(gold, octagon(0.17))
fill(red, octagon(0.11))

data = encode()

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
os.makedirs(os.path.join(root, 'build'), exist_ok=True)
with open(os.path.join(root, 'build', 'icon.hvif'), 'wb') as f:
    f.write(data)

hexstr = data.hex()
lines = ['\t$"' + hexstr[i:i + 64] + '"' for i in range(0, len(hexstr), 64)]
rdef = '''/* Generated by tools/make_icon.py - do not edit by hand. */
resource app_signature "application/x-vnd.rainygirl-princeofpersia";

resource app_flags B_SINGLE_LAUNCH;

resource app_version {
	major  = 1,
	middle = 0,
	minor  = 0,
	variety = B_APPV_FINAL,
	internal = 0,
	short_info = "Prince of Persia",
	long_info = "Prince of Persia (1990, DOS v1.4 data) running natively on Haiku"
};

resource vector_icon array {
%s
};
''' % '\n'.join(lines)

with open(os.path.join(root, 'resources', 'PrinceOfPersia.rdef'), 'w') as f:
    f.write(rdef)
print('wrote resources/PrinceOfPersia.rdef and build/icon.hvif (%d bytes of HVIF)' % len(data))
